name: Application CI/CD Production
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  pipeline:
    name: Build Image
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.pull_request.title, '[skip ci]') && !contains(github.event.pull_request.title, '[ci skip]')"
    timeout-minutes: 40
    env:
      SPRING_OUTPUT_ANSI_ENABLED: DETECT
      SPRING_JPA_SHOW_SQL: false
      NG_CLI_ANALYTICS: false
      GITHUB_USER_REF: ${{ secrets.GH_PACKAGE_REPO_USERNAME }}
      GITHUB_TOKEN_REF: ${{ secrets.GH_PACKAGE_REPO_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: 'github'
          server-username: GITHUB_USER_REF
          server-password: GITHUB_TOKEN_REF
      - name: Cache
        uses: actions/cache@v2.1.5
        with:
          key: apnmt-paymentservice-aws
          path: |
            ~/.m2/repository
            ~/.m2/wrapper
      - name: Remove SNAPSHOT
        run: |
          mvn versions:set -DremoveSnapshot
      - name: Set Release version env variable
        run: |
          echo "RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
      - name: Run tests
        run: |
          chmod +x mvnw
          ./mvnw verify
      - name: Package application
        run: ./mvnw package -Pprod -DskipTests
      - name: Upload to S3
        run: |
          aws s3 cp target/paymentservice-${RELEASE_VERSION}.jar s3://apnmt-aws-applications/paymentservice.jar
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'eu-central-1'
